- inc/head.php
Note: while keymanweb.com does not currently have a staging environment, I have left the environment string for sentry the same as for the other sites as it doesn't hurt and reduces maintenance cost.
> fix: sentry environment

- .gitignore
- App_Data/jobs/triggered/cache_keyboards/run.php
- App_Data/jobs/triggered/cache_keyboards/settings.job
- inc/head.php
- inc/servervars.php
- prog/keyboards.php
1. (inc/head.php, inc/servervars.php, prog/keyboards.php) Makes keymanweb.com responsible for loading the cloud keyboards and making them available to keymanweb.
2. (.gitignore, App_Data/*, prog/keyboards.php) Adds a cache for the cloud keyboards that is refreshed on the back-end every five minutes, and caches the catalog both in cloudflare and in user browser in the meantime.
3. Fixes #17 by moving responsibility for activating keyboard to this website, and tidying up interaction with the cookie.
4. Refactors a few pieces of the Javascript code to reduce the complexity and allow sharing of code with keyboards.php
5. Ensures the message textarea is focused after the keyboard loads.
6. Cleans up a variety of old code (move js loads back inline as this is no longer a real performance …
> fix: Improve load performance and stability

- inc/head.php
- inc/servervars.php
Fixes #19.
Makes two changes:
1. Whenever we move to a beta cycle, keymanweb.com will default to use of the new beta version.  (Detected by beta's major version exceeding stable's.)
- Future enhancement idea:  some sort of link / note when in alpha or beta mode to ease swapping to 'stable'.  (In case users run into an issue.)
2. If KMW's `getDebugInfo` method is available, keymanweb.com will auto-tag all generated Sentry reports with its returned metadata.
- I've also added basic version-tagging for the reports, adopting KMW's version as the site's "version".
- I threw it in as a potential "good idea", since many of the reports really are KMW reports... but I can understand if I should revert this aspect.
- Theis method only exists as of KMW 14.0, as it was implemented partway through the …
> chore: automatically use web's beta during beta cycles

- _common/KeymanHosts.php
- cdn/dev/css/kmw-desktop.css
- cdn/dev/css/kmw-mobile.css
- cdn/dev/css/kmw-tablet.css
- inc/head.php
- inc/servervars.php
- index.php
Fixes #21.
The banner shows only when we are in a beta phase.
and for good measure, what users see if they return to the stable version:
I think you can figure out what that'll look like on the other form factors 😆
> feat: add a banner for pre-release announcement

- cdn/dev/js/kmwlive.js
Fixes #26.
Mitigates (and _may_ fix) #27.
Moves all KMW-dependent code (including the 'kmw-disabled' removal bit that fixes #26) until the window has fully loaded, meaning that _all_ script resources (like KMW) have loaded.  The old placement of the code could trigger at the 'interactive' state, and before KMW's script loaded at that... which would naturally cause null reference errors.
Note that the clipboard may not work on old iOS devices, but that limitation is due to Safari's support for the underlying command - it's only supported at and after iOS 10.  Unfortunately, the mobile layout gives no indication of failure due to use of an older iOS version.
There are a few additional spots in code that may allow #27 to continue occurring; additional work is suggested in these regards. …
> fix: delays kmw-dependent code 'til full page load

- prog/languageexample.php
Fixes #30.
To be safe, I went back to the initial-seed commit; even there, `openALink` was not defined within the repo.  Pretty sure it's been dead this whole time.
> fix: removes use of undefined handler

- inc/servervars.php
Relates to keymanapp/api.keyman.com#157.
See also keymanapp/api.keyman.com#159, keymanapp/help.keyman.com#475.
This updates the version api query to use the new `all` tier and thus we get the benefit of the new s.keyman.com synchronisation and stop using an internal downloads.keyman.com API at the same time.
> fix: use new api for retrieving KeymanWeb version 🛅

- prog/keyboards.php
Fixes keymanapp/keyman#5904.
The cached lookup of KeymanWeb keyboards should not include a timerid, because KeymanWeb has not setup a corresponding promise to resolve with.
I am also about to push a fix to KeymanWeb to avoid issues if the timerid is present but not valid.
> fix: bad use of timerid in cached keyboard lookup

- cdn/dev/js/kmwlive.js
We still have regular downlevel browser visits to keymanweb.com. This fixes one sentry report:
https://sentry.io/organizations/keyman/issues/3122414112/?project=5983523
Fixes KEYMANWEB-COM-7P.
> fix: let to var

- cdn/dev/js/kmwlive.js
Fixes #57.
Fixes KEYMANWEB-COM-2W
Assumption I am making is that `keyman.osk` is not yet init, even if the script is loaded.
> fix: don't attempt to set OSK size before layout is complete

- cdn/dev/js/kmwlive.js
Fixes KEYMANWEB-COM-6.
This crash could happen if the page load event happened before KeymanWeb had loaded and initialized.
The load event is no longer required as we have a minimum of version 14 of KeymanWeb, which has a Promise for post-initialization.
A secondary fix is to use `window.keyman` instead of plain `keyman`, which guarantees a return of `undefined` instead of a `ReferenceError`. There are some other calls that depend on this behaviour.
> fix: remove load event

- .gitignore
- build.sh
Incorporates similar change from keymanapp/help.keyman.com#685 of moving the `./build.sh configure` step to the end of `start`.
> chore: Move build.sh configure step to start 🦭

- inc/servervars.php
Manually update the fallback version of KeymanWeb from 15.0.272 stable to 16.0.143 stable.
While troubleshooting my development tier on the staging branch, I noticed the KeymanWeb fallback version was out of date. (For when network configuration is wrong and keymanweb.com has issues connecting to other Keyman sites)
> chore: Update fallback version of KeymanWeb

- build.sh
- cdn/dev/js/kmwlive.js
- cdn/dev/keys/keyrenderer.js
- inc/head.php
- inc/servervars.php
Relates to keymanapp/keyman.com#403
Since the Keyman websites are using a consistent set of KeymanHosts, this refactors servervars to use KeymanHosts.
* Also removes the need for string manipulations with the site protocol
* Includes a :cherries: pick of #93 to staging
* Fix the builder test action (checks PHP errors)
TODO:
* local api.keyman.com
* local keymanweb.com
> refactor: Update servervars to use KeymanHosts 🦭

- cdn/dev/js/kmwlive.js
- inc/head.php
Fixes #101.
Also fixes the sentry reporting (which will need to be revisited later once we cleanup KeymanHosts).
> fix: use relative URL for language example lookup

- cdn/dev/js/kmwlive.js
Fixes #78.
Once upon a refactor, lost in the deep dark mists of time, a line of code was missed. This change restores that line to its position of glory.
> fix: link subscribe button to mailchimp form

- .github/workflows/ci.yml
- cdn/dev/css/kmw-desktop.css
- cdn/dev/keys/keys.css
- prog/languageexample.php
- prog/renderLanguageExample.php
Adds support for the new 17.0 kps examples object, using `<kbd>` tags for the new format, and tweaks the layout slightly. Formatting changes are a stop-gap only before we move to a fully refreshed design.
Fixes: #89
> feat: support v17 language examples and tweak layout

- .gitignore
- .htaccess
- build.sh
Relates-to: keymanapp/keyman.com#494
Depends-on: keymanapp/shared-sites#38
> chore: support debug mode

- build.sh
- inc/servervars.php
- prog/renderLanguageExample.php
* Splits the server-side and client-side references to keyman sites so that docker-based PHP can reference host.docker.internal on development machines for cross-references.
Relates-to: keymanapp/shared-sites#53
Relates-to: keymanapp/keyman.com#545
Relates-to: keymanapp/api.keyman.com#272
> refactor: clean up KeymanHosts usage and make consistent

- build.sh
- cdn/dev/js/sentry.js
- inc/head.php
* Updates Sentry to 9.1.0
* Moves sentry initialization code into sentry.js
* Adds window.error handler to capture resource loading errors (e.g.
script, link, img)
This change does not refactor to use the common KeymanSentry class, as that involves considerably more work, but it's a good stepping stone on the way to that eventually.
Depends-on: keymanapp/shared-sites#54
Relates-to: #132
> chore: update sentry version, cleanup, and collect resource errors

- robots.txt
Similar to keymanapp/help.keyman.com#2013 on help.keyman-staging.com
This site previously didn't have a robots.txt file
> fix: Disallow all bots since staging site doesn't need to be indexed

- .github/workflows/auto-approve-and-merge-keyman-server-pr.yml
Relates-to: keymanapp/keyman.com#601
Test-bot: skip
> maint: add auto approve action
