keymanapp/keymanweb.com

inc/head.php

This allows ?version parameter to be specified in
the url for keymanweb.com, to override the default,
making it much easier to load a particular version
for testing or reference purposes.

feat: allow specific version

---

index.php

Addresses updating the privacy policy for keymanapp/keyman.com#41

Update privacy policy

---

inc/head.php

I tested these changes through https://github.com/keymanapp/keyman/pull/4253, implementing similar changes for KMW's samples.
Fixes https://github.com/keymanapp/keyman/issues/4143... outside of the help.keyman.com documentation aspects, anyway.

change:  adds keyboards after KMW init via Promise

---

inc/head.php

Completely forgot to apply the last suggestions there before merging the PR, sorry.

chore: applies final suggestion from #20's review

---

inc/head.php

fix: replaces 'let' with 'var'

---

cdn/dev/css/kmw-desktop.css
cdn/dev/css/kmw-mobile.css
inc/head.php
index.php

fixes #40.
Adds version number string to footer and as a tooltip to the KeymanWeb.com logo.

feat: show version number

---

cdn/dev/js/kmwlive.js
inc/head.php

fix: do additional init after kmw promise resolves

---

index.php

The /about/ link at the bottom of the page doesn't exist.

chore: Fix about/ link

---

index.php

fix: link to sil in image

---

cdn/dev/js/kmwlive.js
inc/head.php
index.php

Fixes #50.
Minor tidy up also.

fix: download link breaks after switching keyboard

---

cdn/dev/css/kmw-desktop.css
cdn/dev/js/kmwlive.js
inc/head.php
index.php

One of three PRs fixing https://github.com/keymanapp/keyman/issues/4785.
Note that this relies upon https://github.com/keymanapp/r.keymanweb.com/pull/7, one of the other two PRs contributing to the fix.

change: uses centralized bookmarklet resource 🔖

---

inc/servervars.php

Updates the latest known version of KeymanWeb stable

chore: Update latest known version to 15.0.272

---

inc/servervars.php

fix: fallback kmw version if fails to load

---

.htaccess
Dockerfile
_common/KeymanHosts.php
_include/autoload.php
build.sh
cdn/cdnrefresh.php
inc/servervars.php
resources/builder.inc.sh
resources/keyman-site.conf

part of keymanapp/keyman.com#337 for keymanweb.com and follows the pattern for help.keyman.com and s.keyman.com
* Also incorporates common bits in KeymanHosts.php and autoload.php (Though I don't think any PHP is using the `Keyman\Site\com\keymanweb` namespace)
Questions:
* servervars.php seems to have diverged from the other common ones?
For Docker, the site will run locally at
http://localhost:8057
I did need to these local overrides in KeymanHosts.php (not checked into this PR)
```php
$this->s_keyman_com = "https://s.keyman.com";
$this->api_keyman_com = "https://api.keyman.com";
$this->downloads_keyman_com = "https://downloads.keyman.com";
```
Commit https://github.com/keymanapp/keymanweb.com/pull/63/commits/87972e14bd4f5693cd7a32e8da87d8d6073c7966 brings in similar changes as …

feat: Run site with Docker

---

inc/head.php

To accompany https://github.com/keymanapp/keyman/pull/8560 when it lands.

change: setActiveOnRegister now boolean in KMW 17.0

---

_common/KeymanHosts.php
build.sh

Addresses review comment from https://github.com/darcywong00/reverse-proxy/pull/1#discussion_r1324068800
* Also cleanup build.sh

chore: Update site_suffix with KEYMAN_COM_PROXY_PORT 🦭

---

.gitattributes
.github/workflows/ci.yml
build.sh
resources/init-container.sh

Progress for keymanapp/keyman.com#337
* Add init-container.sh to generate CDN
* Update build.sh with latest shared sites infrastructure
* Add testing

chore: Add init-container.sh

---

.gitattributes
.github/workflows/ci.yml
build.sh
phpunit.xml
tests/InfrastructureTest.php

Continuing keymanapp/keyman.com#337; Follows #83 and #85
* Run a PHP unit test

chore: Add unit test

---

build.sh

:cherries: pick of #99 for production branch

cherrypick: Update production to use shared-sites v0.4 :cherries: 

---

cdn/dev/js/kmwlive.js

fix: adds #message-value retrieval null-guard

---

inc/head.php

fix: select tier based on passed-in version

---

.github/workflows/ci.yml
build.sh
inc/servervars.php

This is to pull in the bootstrap changes from ~keymanapp/shared-sites#20.~ keymanapp/shared-sites#28
~The site doesn't load locally for me, but I haven't been able to troubleshoot why.~
Fixing up site_suffix gets the site to load now.

chore: Update BOOTSTRAP_VERSION to 0.10

---

build.sh
resources/init-container.sh

Follows https://github.com/keymanapp/keyman.com/pull/471 and implements onto keymanweb.
This PR is ready for review.

fix: Skip generating cdn/deploy with ./build.sh <action> --debug

---

.github/workflows/ci.yml

Fixes #128 updating ci.yml to use ubuntu-latest

chore: Update ci.yml to ubuntu-latest

---

.github/multi-labeler.yml
.github/workflows/labeler.yml

End of sprint task
Test-bot: skip

chore: Merge master to staging for Sprint A19S9

---

build.sh

Update BOOTSTRAP_VERSION to [v1.0.4](https://github.com/keymanapp/shared-sites/releases/tag/v1.0.4).

auto: update shared-sites version to v1.0.4
